import Head from 'next/head';
import {useSession,signIn,signOut} from 'next-auth/react'

export default function Home() {

  const {data:session} = useSession()

  return (
    <>
      <Head>
        <title>Next Google Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="cont">
            {
              (!session)?
              <>
                <h3></h3>
                <button onClick={()=>signIn()}>Login</button>
              </>
              :<>
                <h3>Hello, {session.user.name} {session.user.email}</h3>
                <button onClick={()=>signOut()}>SignOut</button>
              </>
            }
            
        </div>
      </main>
    </>
  )
}
